.PHONY: all build test lint generate migrate fmt vet tidy run proto docker-up docker-down docker-logs

# Published binary name. Override to ship under a different name without
# touching the source tree, e.g. `make build BIN_NAME=msgsvc`.
# The Go package path stays cmd/server regardless.
BIN_NAME := message-service
CMD_DIR  := cmd/server

## build: Build the message-service binary (server + migrate in one)
build:
	go build -o bin/$(BIN_NAME) ./$(CMD_DIR)/

## run: Run the server locally
run:
	@test -f config.yaml || cp config.example.yaml config.yaml
	go run ./$(CMD_DIR)/

## test: Run tests with race detector
test:
	go test -race -coverprofile=coverage.out ./...

## lint: Run golangci-lint
lint:
	golangci-lint run ./...

## fmt: Format code
fmt:
	gofmt -w .
	goimports -w .

## vet: Run go vet
vet:
	go vet ./...

## generate: Run gorm.io/cli code generation
generate:
	gorm gen -i ./internal/store/models -o ./internal/store/generated

## migrate: Run database migrations (AutoMigrate) via the unified binary
migrate:
	@test -f config.yaml || cp config.example.yaml config.yaml
	go run ./$(CMD_DIR) migrate

## proto: Generate protobuf code with buf
proto:
	buf generate

## tidy: Run go mod tidy
tidy:
	go mod tidy

## all: Format, vet, lint, test
all: fmt vet lint test

# BEGIN service-docker-scaffold
# Generated by service-docker-scaffold. Rerendering replaces this entire block.

IMAGE_REPOSITORY ?= message-service
IMAGE_TAG ?= latest
TARGET_PLATFORM ?=
DOCKER_PLATFORM_ENV = $(if $(strip $(TARGET_PLATFORM)),DOCKER_DEFAULT_PLATFORM=$(TARGET_PLATFORM))
DOCKER_COMPOSE := $(DOCKER_PLATFORM_ENV) IMAGE_REPOSITORY=$(IMAGE_REPOSITORY) IMAGE_TAG=$(IMAGE_TAG) docker compose

.PHONY: docker-build docker-push docker-up docker-migrate docker-down docker-reset docker-logs docker-health

## docker-build: Build the host platform, or pass TARGET_PLATFORM=linux/amd64
docker-build:
	$(DOCKER_COMPOSE) build

## docker-push: Push $(IMAGE_REPOSITORY):$(IMAGE_TAG)
docker-push: docker-build
	$(DOCKER_COMPOSE) push message-service

## docker-up: Build and start the selected stack, then wait for healthchecks
docker-up: docker-build
	$(DOCKER_COMPOSE) up --wait --no-build -d

## docker-migrate: One-shot migration against the compose DB (builds, starts deps, runs migrate, exits)
docker-migrate: docker-build
	$(DOCKER_COMPOSE) run --rm message-service migrate

## docker-down: Stop containers while preserving named volumes
docker-down:
	$(DOCKER_COMPOSE) down

## docker-reset: Stop containers and deliberately delete named volumes
docker-reset:
	@echo "Deleting Docker volumes for message-service"
	$(DOCKER_COMPOSE) down -v

## docker-logs: Follow logs for all services, or pass svc=<service>
docker-logs:
	$(DOCKER_COMPOSE) logs -f --tail=100 $(svc)

## docker-health: Query grpcx health from inside the app container
docker-health:
	$(DOCKER_COMPOSE) exec -T message-service grpc_health_probe -addr=127.0.0.1:19092

# END service-docker-scaffold
