package region

// regionTable is the international dial-code directory: ISO 3166-1 alpha-2,
// ITU E.164 dial code (with "+"), and CLDR display names. Generated from
// libphonenumber-js metadata + ICU at dev time (see web/scripts/gen-region-codes.js
// for the same source feeding the frontend historical copy); sorted zh-Hans.
var regionTable = []Entry{
	{Code: "AL", DialCode: "+355", NameZh: "阿尔巴尼亚", NameEn: "Albania"},
	{Code: "DZ", DialCode: "+213", NameZh: "阿尔及利亚", NameEn: "Algeria"},
	{Code: "AF", DialCode: "+93", NameZh: "阿富汗", NameEn: "Afghanistan"},
	{Code: "AR", DialCode: "+54", NameZh: "阿根廷", NameEn: "Argentina"},
	{Code: "AE", DialCode: "+971", NameZh: "阿拉伯联合酋长国", NameEn: "United Arab Emirates"},
	{Code: "AW", DialCode: "+297", NameZh: "阿鲁巴", NameEn: "Aruba"},
	{Code: "OM", DialCode: "+968", NameZh: "阿曼", NameEn: "Oman"},
	{Code: "AZ", DialCode: "+994", NameZh: "阿塞拜疆", NameEn: "Azerbaijan"},
	{Code: "AC", DialCode: "+247", NameZh: "阿森松岛", NameEn: "Ascension Island"},
	{Code: "EG", DialCode: "+20", NameZh: "埃及", NameEn: "Egypt"},
	{Code: "ET", DialCode: "+251", NameZh: "埃塞俄比亚", NameEn: "Ethiopia"},
	{Code: "IE", DialCode: "+353", NameZh: "爱尔兰", NameEn: "Ireland"},
	{Code: "EE", DialCode: "+372", NameZh: "爱沙尼亚", NameEn: "Estonia"},
	{Code: "AD", DialCode: "+376", NameZh: "安道尔", NameEn: "Andorra"},
	{Code: "AO", DialCode: "+244", NameZh: "安哥拉", NameEn: "Angola"},
	{Code: "AI", DialCode: "+1", NameZh: "安圭拉", NameEn: "Anguilla"},
	{Code: "AG", DialCode: "+1", NameZh: "安提瓜和巴布达", NameEn: "Antigua & Barbuda"},
	{Code: "AT", DialCode: "+43", NameZh: "奥地利", NameEn: "Austria"},
	{Code: "AX", DialCode: "+358", NameZh: "奥兰群岛", NameEn: "Åland Islands"},
	{Code: "AU", DialCode: "+61", NameZh: "澳大利亚", NameEn: "Australia"},
	{Code: "BB", DialCode: "+1", NameZh: "巴巴多斯", NameEn: "Barbados"},
	{Code: "PG", DialCode: "+675", NameZh: "巴布亚新几内亚", NameEn: "Papua New Guinea"},
	{Code: "BS", DialCode: "+1", NameZh: "巴哈马", NameEn: "Bahamas"},
	{Code: "PK", DialCode: "+92", NameZh: "巴基斯坦", NameEn: "Pakistan"},
	{Code: "PY", DialCode: "+595", NameZh: "巴拉圭", NameEn: "Paraguay"},
	{Code: "PS", DialCode: "+970", NameZh: "巴勒斯坦领土", NameEn: "Palestinian Territories"},
	{Code: "BH", DialCode: "+973", NameZh: "巴林", NameEn: "Bahrain"},
	{Code: "PA", DialCode: "+507", NameZh: "巴拿马", NameEn: "Panama"},
	{Code: "BR", DialCode: "+55", NameZh: "巴西", NameEn: "Brazil"},
	{Code: "BY", DialCode: "+375", NameZh: "白俄罗斯", NameEn: "Belarus"},
	{Code: "BM", DialCode: "+1", NameZh: "百慕大", NameEn: "Bermuda"},
	{Code: "BG", DialCode: "+359", NameZh: "保加利亚", NameEn: "Bulgaria"},
	{Code: "MP", DialCode: "+1", NameZh: "北马里亚纳群岛", NameEn: "Northern Mariana Islands"},
	{Code: "MK", DialCode: "+389", NameZh: "北马其顿", NameEn: "North Macedonia"},
	{Code: "BJ", DialCode: "+229", NameZh: "贝宁", NameEn: "Benin"},
	{Code: "BE", DialCode: "+32", NameZh: "比利时", NameEn: "Belgium"},
	{Code: "IS", DialCode: "+354", NameZh: "冰岛", NameEn: "Iceland"},
	{Code: "PR", DialCode: "+1", NameZh: "波多黎各", NameEn: "Puerto Rico"},
	{Code: "PL", DialCode: "+48", NameZh: "波兰", NameEn: "Poland"},
	{Code: "BA", DialCode: "+387", NameZh: "波斯尼亚和黑塞哥维那", NameEn: "Bosnia & Herzegovina"},
	{Code: "BO", DialCode: "+591", NameZh: "玻利维亚", NameEn: "Bolivia"},
	{Code: "BZ", DialCode: "+501", NameZh: "伯利兹", NameEn: "Belize"},
	{Code: "BW", DialCode: "+267", NameZh: "博茨瓦纳", NameEn: "Botswana"},
	{Code: "BT", DialCode: "+975", NameZh: "不丹", NameEn: "Bhutan"},
	{Code: "BF", DialCode: "+226", NameZh: "布基纳法索", NameEn: "Burkina Faso"},
	{Code: "BI", DialCode: "+257", NameZh: "布隆迪", NameEn: "Burundi"},
	{Code: "KP", DialCode: "+850", NameZh: "朝鲜", NameEn: "North Korea"},
	{Code: "GQ", DialCode: "+240", NameZh: "赤道几内亚", NameEn: "Equatorial Guinea"},
	{Code: "DK", DialCode: "+45", NameZh: "丹麦", NameEn: "Denmark"},
	{Code: "DE", DialCode: "+49", NameZh: "德国", NameEn: "Germany"},
	{Code: "TL", DialCode: "+670", NameZh: "东帝汶", NameEn: "Timor-Leste"},
	{Code: "TG", DialCode: "+228", NameZh: "多哥", NameEn: "Togo"},
	{Code: "DO", DialCode: "+1", NameZh: "多米尼加共和国", NameEn: "Dominican Republic"},
	{Code: "DM", DialCode: "+1", NameZh: "多米尼克", NameEn: "Dominica"},
	{Code: "RU", DialCode: "+7", NameZh: "俄罗斯", NameEn: "Russia"},
	{Code: "EC", DialCode: "+593", NameZh: "厄瓜多尔", NameEn: "Ecuador"},
	{Code: "ER", DialCode: "+291", NameZh: "厄立特里亚", NameEn: "Eritrea"},
	{Code: "FR", DialCode: "+33", NameZh: "法国", NameEn: "France"},
	{Code: "FO", DialCode: "+298", NameZh: "法罗群岛", NameEn: "Faroe Islands"},
	{Code: "PF", DialCode: "+689", NameZh: "法属波利尼西亚", NameEn: "French Polynesia"},
	{Code: "GF", DialCode: "+594", NameZh: "法属圭亚那", NameEn: "French Guiana"},
	{Code: "MF", DialCode: "+590", NameZh: "法属圣马丁", NameEn: "St. Martin"},
	{Code: "VA", DialCode: "+39", NameZh: "梵蒂冈", NameEn: "Vatican City"},
	{Code: "PH", DialCode: "+63", NameZh: "菲律宾", NameEn: "Philippines"},
	{Code: "FJ", DialCode: "+679", NameZh: "斐济", NameEn: "Fiji"},
	{Code: "FI", DialCode: "+358", NameZh: "芬兰", NameEn: "Finland"},
	{Code: "CV", DialCode: "+238", NameZh: "佛得角", NameEn: "Cape Verde"},
	{Code: "FK", DialCode: "+500", NameZh: "福克兰群岛", NameEn: "Falkland Islands"},
	{Code: "GM", DialCode: "+220", NameZh: "冈比亚", NameEn: "Gambia"},
	{Code: "CG", DialCode: "+242", NameZh: "刚果（布）", NameEn: "Congo - Brazzaville"},
	{Code: "CD", DialCode: "+243", NameZh: "刚果（金）", NameEn: "Congo - Kinshasa"},
	{Code: "CO", DialCode: "+57", NameZh: "哥伦比亚", NameEn: "Colombia"},
	{Code: "CR", DialCode: "+506", NameZh: "哥斯达黎加", NameEn: "Costa Rica"},
	{Code: "GD", DialCode: "+1", NameZh: "格林纳达", NameEn: "Grenada"},
	{Code: "GL", DialCode: "+299", NameZh: "格陵兰", NameEn: "Greenland"},
	{Code: "GE", DialCode: "+995", NameZh: "格鲁吉亚", NameEn: "Georgia"},
	{Code: "GG", DialCode: "+44", NameZh: "根西岛", NameEn: "Guernsey"},
	{Code: "CU", DialCode: "+53", NameZh: "古巴", NameEn: "Cuba"},
	{Code: "GP", DialCode: "+590", NameZh: "瓜德罗普", NameEn: "Guadeloupe"},
	{Code: "GU", DialCode: "+1", NameZh: "关岛", NameEn: "Guam"},
	{Code: "GY", DialCode: "+592", NameZh: "圭亚那", NameEn: "Guyana"},
	{Code: "KZ", DialCode: "+7", NameZh: "哈萨克斯坦", NameEn: "Kazakhstan"},
	{Code: "HT", DialCode: "+509", NameZh: "海地", NameEn: "Haiti"},
	{Code: "KR", DialCode: "+82", NameZh: "韩国", NameEn: "South Korea"},
	{Code: "NL", DialCode: "+31", NameZh: "荷兰", NameEn: "Netherlands"},
	{Code: "BQ", DialCode: "+599", NameZh: "荷属加勒比区", NameEn: "Caribbean Netherlands"},
	{Code: "SX", DialCode: "+1", NameZh: "荷属圣马丁", NameEn: "Sint Maarten"},
	{Code: "ME", DialCode: "+382", NameZh: "黑山", NameEn: "Montenegro"},
	{Code: "HN", DialCode: "+504", NameZh: "洪都拉斯", NameEn: "Honduras"},
	{Code: "KI", DialCode: "+686", NameZh: "基里巴斯", NameEn: "Kiribati"},
	{Code: "DJ", DialCode: "+253", NameZh: "吉布提", NameEn: "Djibouti"},
	{Code: "KG", DialCode: "+996", NameZh: "吉尔吉斯斯坦", NameEn: "Kyrgyzstan"},
	{Code: "GN", DialCode: "+224", NameZh: "几内亚", NameEn: "Guinea"},
	{Code: "GW", DialCode: "+245", NameZh: "几内亚比绍", NameEn: "Guinea-Bissau"},
	{Code: "CA", DialCode: "+1", NameZh: "加拿大", NameEn: "Canada"},
	{Code: "GH", DialCode: "+233", NameZh: "加纳", NameEn: "Ghana"},
	{Code: "GA", DialCode: "+241", NameZh: "加蓬", NameEn: "Gabon"},
	{Code: "KH", DialCode: "+855", NameZh: "柬埔寨", NameEn: "Cambodia"},
	{Code: "CZ", DialCode: "+420", NameZh: "捷克", NameEn: "Czechia"},
	{Code: "ZW", DialCode: "+263", NameZh: "津巴布韦", NameEn: "Zimbabwe"},
	{Code: "CM", DialCode: "+237", NameZh: "喀麦隆", NameEn: "Cameroon"},
	{Code: "QA", DialCode: "+974", NameZh: "卡塔尔", NameEn: "Qatar"},
	{Code: "KY", DialCode: "+1", NameZh: "开曼群岛", NameEn: "Cayman Islands"},
	{Code: "CC", DialCode: "+61", NameZh: "科科斯（基林）群岛", NameEn: "Cocos (Keeling) Islands"},
	{Code: "KM", DialCode: "+269", NameZh: "科摩罗", NameEn: "Comoros"},
	{Code: "XK", DialCode: "+383", NameZh: "科索沃", NameEn: "Kosovo"},
	{Code: "CI", DialCode: "+225", NameZh: "科特迪瓦", NameEn: "Côte d’Ivoire"},
	{Code: "KW", DialCode: "+965", NameZh: "科威特", NameEn: "Kuwait"},
	{Code: "HR", DialCode: "+385", NameZh: "克罗地亚", NameEn: "Croatia"},
	{Code: "KE", DialCode: "+254", NameZh: "肯尼亚", NameEn: "Kenya"},
	{Code: "CK", DialCode: "+682", NameZh: "库克群岛", NameEn: "Cook Islands"},
	{Code: "CW", DialCode: "+599", NameZh: "库拉索", NameEn: "Curaçao"},
	{Code: "LV", DialCode: "+371", NameZh: "拉脱维亚", NameEn: "Latvia"},
	{Code: "LS", DialCode: "+266", NameZh: "莱索托", NameEn: "Lesotho"},
	{Code: "LA", DialCode: "+856", NameZh: "老挝", NameEn: "Laos"},
	{Code: "LB", DialCode: "+961", NameZh: "黎巴嫩", NameEn: "Lebanon"},
	{Code: "LT", DialCode: "+370", NameZh: "立陶宛", NameEn: "Lithuania"},
	{Code: "LR", DialCode: "+231", NameZh: "利比里亚", NameEn: "Liberia"},
	{Code: "LY", DialCode: "+218", NameZh: "利比亚", NameEn: "Libya"},
	{Code: "LI", DialCode: "+423", NameZh: "列支敦士登", NameEn: "Liechtenstein"},
	{Code: "RE", DialCode: "+262", NameZh: "留尼汪", NameEn: "Réunion"},
	{Code: "LU", DialCode: "+352", NameZh: "卢森堡", NameEn: "Luxembourg"},
	{Code: "RW", DialCode: "+250", NameZh: "卢旺达", NameEn: "Rwanda"},
	{Code: "RO", DialCode: "+40", NameZh: "罗马尼亚", NameEn: "Romania"},
	{Code: "MG", DialCode: "+261", NameZh: "马达加斯加", NameEn: "Madagascar"},
	{Code: "IM", DialCode: "+44", NameZh: "马恩岛", NameEn: "Isle of Man"},
	{Code: "MV", DialCode: "+960", NameZh: "马尔代夫", NameEn: "Maldives"},
	{Code: "MT", DialCode: "+356", NameZh: "马耳他", NameEn: "Malta"},
	{Code: "MW", DialCode: "+265", NameZh: "马拉维", NameEn: "Malawi"},
	{Code: "MY", DialCode: "+60", NameZh: "马来西亚", NameEn: "Malaysia"},
	{Code: "ML", DialCode: "+223", NameZh: "马里", NameEn: "Mali"},
	{Code: "MH", DialCode: "+692", NameZh: "马绍尔群岛", NameEn: "Marshall Islands"},
	{Code: "MQ", DialCode: "+596", NameZh: "马提尼克", NameEn: "Martinique"},
	{Code: "YT", DialCode: "+262", NameZh: "马约特", NameEn: "Mayotte"},
	{Code: "MU", DialCode: "+230", NameZh: "毛里求斯", NameEn: "Mauritius"},
	{Code: "MR", DialCode: "+222", NameZh: "毛里塔尼亚", NameEn: "Mauritania"},
	{Code: "US", DialCode: "+1", NameZh: "美国", NameEn: "United States"},
	{Code: "AS", DialCode: "+1", NameZh: "美属萨摩亚", NameEn: "American Samoa"},
	{Code: "VI", DialCode: "+1", NameZh: "美属维尔京群岛", NameEn: "U.S. Virgin Islands"},
	{Code: "MN", DialCode: "+976", NameZh: "蒙古", NameEn: "Mongolia"},
	{Code: "MS", DialCode: "+1", NameZh: "蒙特塞拉特", NameEn: "Montserrat"},
	{Code: "BD", DialCode: "+880", NameZh: "孟加拉国", NameEn: "Bangladesh"},
	{Code: "PE", DialCode: "+51", NameZh: "秘鲁", NameEn: "Peru"},
	{Code: "FM", DialCode: "+691", NameZh: "密克罗尼西亚", NameEn: "Micronesia"},
	{Code: "MM", DialCode: "+95", NameZh: "缅甸", NameEn: "Myanmar (Burma)"},
	{Code: "MD", DialCode: "+373", NameZh: "摩尔多瓦", NameEn: "Moldova"},
	{Code: "MA", DialCode: "+212", NameZh: "摩洛哥", NameEn: "Morocco"},
	{Code: "MC", DialCode: "+377", NameZh: "摩纳哥", NameEn: "Monaco"},
	{Code: "MZ", DialCode: "+258", NameZh: "莫桑比克", NameEn: "Mozambique"},
	{Code: "MX", DialCode: "+52", NameZh: "墨西哥", NameEn: "Mexico"},
	{Code: "NA", DialCode: "+264", NameZh: "纳米比亚", NameEn: "Namibia"},
	{Code: "ZA", DialCode: "+27", NameZh: "南非", NameEn: "South Africa"},
	{Code: "SS", DialCode: "+211", NameZh: "南苏丹", NameEn: "South Sudan"},
	{Code: "NR", DialCode: "+674", NameZh: "瑙鲁", NameEn: "Nauru"},
	{Code: "NI", DialCode: "+505", NameZh: "尼加拉瓜", NameEn: "Nicaragua"},
	{Code: "NP", DialCode: "+977", NameZh: "尼泊尔", NameEn: "Nepal"},
	{Code: "NE", DialCode: "+227", NameZh: "尼日尔", NameEn: "Niger"},
	{Code: "NG", DialCode: "+234", NameZh: "尼日利亚", NameEn: "Nigeria"},
	{Code: "NU", DialCode: "+683", NameZh: "纽埃", NameEn: "Niue"},
	{Code: "NO", DialCode: "+47", NameZh: "挪威", NameEn: "Norway"},
	{Code: "NF", DialCode: "+672", NameZh: "诺福克岛", NameEn: "Norfolk Island"},
	{Code: "PW", DialCode: "+680", NameZh: "帕劳", NameEn: "Palau"},
	{Code: "PT", DialCode: "+351", NameZh: "葡萄牙", NameEn: "Portugal"},
	{Code: "JP", DialCode: "+81", NameZh: "日本", NameEn: "Japan"},
	{Code: "SE", DialCode: "+46", NameZh: "瑞典", NameEn: "Sweden"},
	{Code: "CH", DialCode: "+41", NameZh: "瑞士", NameEn: "Switzerland"},
	{Code: "SV", DialCode: "+503", NameZh: "萨尔瓦多", NameEn: "El Salvador"},
	{Code: "WS", DialCode: "+685", NameZh: "萨摩亚", NameEn: "Samoa"},
	{Code: "RS", DialCode: "+381", NameZh: "塞尔维亚", NameEn: "Serbia"},
	{Code: "SL", DialCode: "+232", NameZh: "塞拉利昂", NameEn: "Sierra Leone"},
	{Code: "SN", DialCode: "+221", NameZh: "塞内加尔", NameEn: "Senegal"},
	{Code: "CY", DialCode: "+357", NameZh: "塞浦路斯", NameEn: "Cyprus"},
	{Code: "SC", DialCode: "+248", NameZh: "塞舌尔", NameEn: "Seychelles"},
	{Code: "SA", DialCode: "+966", NameZh: "沙特阿拉伯", NameEn: "Saudi Arabia"},
	{Code: "BL", DialCode: "+590", NameZh: "圣巴泰勒米", NameEn: "St. Barthélemy"},
	{Code: "CX", DialCode: "+61", NameZh: "圣诞岛", NameEn: "Christmas Island"},
	{Code: "ST", DialCode: "+239", NameZh: "圣多美和普林西比", NameEn: "São Tomé & Príncipe"},
	{Code: "SH", DialCode: "+290", NameZh: "圣赫勒拿", NameEn: "St. Helena"},
	{Code: "KN", DialCode: "+1", NameZh: "圣基茨和尼维斯", NameEn: "St. Kitts & Nevis"},
	{Code: "LC", DialCode: "+1", NameZh: "圣卢西亚", NameEn: "St. Lucia"},
	{Code: "SM", DialCode: "+378", NameZh: "圣马力诺", NameEn: "San Marino"},
	{Code: "PM", DialCode: "+508", NameZh: "圣皮埃尔和密克隆群岛", NameEn: "St. Pierre & Miquelon"},
	{Code: "VC", DialCode: "+1", NameZh: "圣文森特和格林纳丁斯", NameEn: "St. Vincent & Grenadines"},
	{Code: "LK", DialCode: "+94", NameZh: "斯里兰卡", NameEn: "Sri Lanka"},
	{Code: "SK", DialCode: "+421", NameZh: "斯洛伐克", NameEn: "Slovakia"},
	{Code: "SI", DialCode: "+386", NameZh: "斯洛文尼亚", NameEn: "Slovenia"},
	{Code: "SJ", DialCode: "+47", NameZh: "斯瓦尔巴和扬马延", NameEn: "Svalbard & Jan Mayen"},
	{Code: "SZ", DialCode: "+268", NameZh: "斯威士兰", NameEn: "Eswatini"},
	{Code: "SD", DialCode: "+249", NameZh: "苏丹", NameEn: "Sudan"},
	{Code: "SR", DialCode: "+597", NameZh: "苏里南", NameEn: "Suriname"},
	{Code: "SB", DialCode: "+677", NameZh: "所罗门群岛", NameEn: "Solomon Islands"},
	{Code: "SO", DialCode: "+252", NameZh: "索马里", NameEn: "Somalia"},
	{Code: "TJ", DialCode: "+992", NameZh: "塔吉克斯坦", NameEn: "Tajikistan"},
	{Code: "TW", DialCode: "+886", NameZh: "台湾", NameEn: "Taiwan"},
	{Code: "TH", DialCode: "+66", NameZh: "泰国", NameEn: "Thailand"},
	{Code: "TZ", DialCode: "+255", NameZh: "坦桑尼亚", NameEn: "Tanzania"},
	{Code: "TO", DialCode: "+676", NameZh: "汤加", NameEn: "Tonga"},
	{Code: "TC", DialCode: "+1", NameZh: "特克斯和凯科斯群岛", NameEn: "Turks & Caicos Islands"},
	{Code: "TA", DialCode: "+290", NameZh: "特里斯坦-达库尼亚群岛", NameEn: "Tristan da Cunha"},
	{Code: "TT", DialCode: "+1", NameZh: "特立尼达和多巴哥", NameEn: "Trinidad & Tobago"},
	{Code: "TN", DialCode: "+216", NameZh: "突尼斯", NameEn: "Tunisia"},
	{Code: "TV", DialCode: "+688", NameZh: "图瓦卢", NameEn: "Tuvalu"},
	{Code: "TR", DialCode: "+90", NameZh: "土耳其", NameEn: "Türkiye"},
	{Code: "TM", DialCode: "+993", NameZh: "土库曼斯坦", NameEn: "Turkmenistan"},
	{Code: "TK", DialCode: "+690", NameZh: "托克劳", NameEn: "Tokelau"},
	{Code: "WF", DialCode: "+681", NameZh: "瓦利斯和富图纳", NameEn: "Wallis & Futuna"},
	{Code: "VU", DialCode: "+678", NameZh: "瓦努阿图", NameEn: "Vanuatu"},
	{Code: "GT", DialCode: "+502", NameZh: "危地马拉", NameEn: "Guatemala"},
	{Code: "VE", DialCode: "+58", NameZh: "委内瑞拉", NameEn: "Venezuela"},
	{Code: "BN", DialCode: "+673", NameZh: "文莱", NameEn: "Brunei"},
	{Code: "UG", DialCode: "+256", NameZh: "乌干达", NameEn: "Uganda"},
	{Code: "UA", DialCode: "+380", NameZh: "乌克兰", NameEn: "Ukraine"},
	{Code: "UY", DialCode: "+598", NameZh: "乌拉圭", NameEn: "Uruguay"},
	{Code: "UZ", DialCode: "+998", NameZh: "乌兹别克斯坦", NameEn: "Uzbekistan"},
	{Code: "ES", DialCode: "+34", NameZh: "西班牙", NameEn: "Spain"},
	{Code: "EH", DialCode: "+212", NameZh: "西撒哈拉", NameEn: "Western Sahara"},
	{Code: "GR", DialCode: "+30", NameZh: "希腊", NameEn: "Greece"},
	{Code: "SG", DialCode: "+65", NameZh: "新加坡", NameEn: "Singapore"},
	{Code: "NC", DialCode: "+687", NameZh: "新喀里多尼亚", NameEn: "New Caledonia"},
	{Code: "NZ", DialCode: "+64", NameZh: "新西兰", NameEn: "New Zealand"},
	{Code: "HU", DialCode: "+36", NameZh: "匈牙利", NameEn: "Hungary"},
	{Code: "SY", DialCode: "+963", NameZh: "叙利亚", NameEn: "Syria"},
	{Code: "JM", DialCode: "+1", NameZh: "牙买加", NameEn: "Jamaica"},
	{Code: "AM", DialCode: "+374", NameZh: "亚美尼亚", NameEn: "Armenia"},
	{Code: "YE", DialCode: "+967", NameZh: "也门", NameEn: "Yemen"},
	{Code: "IQ", DialCode: "+964", NameZh: "伊拉克", NameEn: "Iraq"},
	{Code: "IR", DialCode: "+98", NameZh: "伊朗", NameEn: "Iran"},
	{Code: "IL", DialCode: "+972", NameZh: "以色列", NameEn: "Israel"},
	{Code: "IT", DialCode: "+39", NameZh: "意大利", NameEn: "Italy"},
	{Code: "IN", DialCode: "+91", NameZh: "印度", NameEn: "India"},
	{Code: "ID", DialCode: "+62", NameZh: "印度尼西亚", NameEn: "Indonesia"},
	{Code: "GB", DialCode: "+44", NameZh: "英国", NameEn: "United Kingdom"},
	{Code: "VG", DialCode: "+1", NameZh: "英属维尔京群岛", NameEn: "British Virgin Islands"},
	{Code: "IO", DialCode: "+246", NameZh: "英属印度洋领地", NameEn: "British Indian Ocean Territory"},
	{Code: "JO", DialCode: "+962", NameZh: "约旦", NameEn: "Jordan"},
	{Code: "VN", DialCode: "+84", NameZh: "越南", NameEn: "Vietnam"},
	{Code: "ZM", DialCode: "+260", NameZh: "赞比亚", NameEn: "Zambia"},
	{Code: "JE", DialCode: "+44", NameZh: "泽西岛", NameEn: "Jersey"},
	{Code: "TD", DialCode: "+235", NameZh: "乍得", NameEn: "Chad"},
	{Code: "GI", DialCode: "+350", NameZh: "直布罗陀", NameEn: "Gibraltar"},
	{Code: "CL", DialCode: "+56", NameZh: "智利", NameEn: "Chile"},
	{Code: "CF", DialCode: "+236", NameZh: "中非共和国", NameEn: "Central African Republic"},
	{Code: "CN", DialCode: "+86", NameZh: "中国", NameEn: "China"},
	{Code: "MO", DialCode: "+853", NameZh: "中国澳门特别行政区", NameEn: "Macao SAR China"},
	{Code: "HK", DialCode: "+852", NameZh: "中国香港特别行政区", NameEn: "Hong Kong SAR China"},
}
